### PR TITLE
feat: build nim_status.a static library and create simple test file in C

### PR DESCRIPTION
**Pull request by richard-ramos**
To test:
```
make update
make
make tests
```

### CODE REVIEW

**Comment by richard-ramos** [comment]
This will create a static library for all the functions defined in here: https://github.com/status-im/nim-status/blob/80d9d2c8b7047987cdff92a44de8b041d2c5fca1/src/nim_status.nim

There are some functions that are still missing, the need for gcref the returned strings is to be determined and the signal callback function is not tested yet. These will come in a new PR.

**Comment by richard-ramos** [comment]
Added the missing functions, and exported a struct for `Identicon` and `GenerateAlias` functions

**Comment by siphiuel** [comment]
thanks @richard-ramos ! 

Builds works, but running `make tests` on macOS produces this: https://gist.github.com/siphiuel/3e9124875ed60c84258ca3ff2433c435. Is this expected at this stage?

**Comment by siphiuel** [comment]
```
➜  nim-status git:(feat/build-static-lib-1) ✗ make tests
Compiling 'test/test'
Executing 'test/test'
{"result":"0xec3608877ecbf8084c29896b7eab2a368b2b3c8d003288584d145613dfa4706c"}
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAk0lEQVR4nOzYwQmEMBQG4exiL1ZjN5ZhN1ZjNXrxaCCQBIaf+Y4iwvAgvPgvIQyhMYTGEBpDaGJClt4PHOd1fz3ft/U34v1WMRMxhMYQGkNoDKExhKZ5v6ntSLO17mAxEzGExhCarltZGXiaeUN8GUJjCE33qVUz6/9VTcxEDKExRJPETMQQGkNoDKExhOYJAAD//7VPFGKMHGOVAAAAAElFTkSuQmCC
```
Works!

**Comment by richard-ramos** [comment]
haha! that's great! :)   I was about to write that I did not know if these libs were enough to fix this issue and ask for help!

**Comment by siphiuel** [comment]
Noticed that generated `libstatus.a` is 727K in size, as opposed to `libstatus.a`, which is ~70M. Not an expert in this, but could it be that static lib is not properly generated?

**Comment by richard-ramos** [comment]
nim_status.a is smaller because it's not linked against status-go libstatus.a
Both nim_status.a and libstatus.a are linked in the final executable, as it is done in the tests target where both libs are mentioned:

```
$(CC) -I"$(CURDIR)/build" -I"$(CURDIR)/vendor/nimbus-build-system/vendor/Nim/lib" test/test.c $(NIMSTATUS) $(STATUSGO) -framework CoreFoundation -framework CoreServices -framework IOKit -framework Security -lm -pthread -o test/test
```

If we want to merge nim_status.a and libstatus.a we should use the `ar` command but I don't think it really provides advantages in this scenario

**Comment by Samyoul** [comment]
Cool the build is working for me

```
Compiling 'test/test'
Executing 'test/test'
{"result":"0xec3608877ecbf8084c29896b7eab2a368b2b3c8d003288584d145613dfa4706c"}
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAk0lEQVR4nOzYwQmEMBQG4exiL1ZjN5ZhN1ZjNXrxaCCQBIaf+Y4iwvAgvPgvIQyhMYTGEBpDaGJClt4PHOd1fz3ft/U34v1WMRMxhMYQGkNoDKExhKZ5v6ntSLO17mAxEzGExhCarltZGXiaeUN8GUJjCE33qVUz6/9VTcxEDKExRJPETMQQGkNoDKExhOYJAAD//7VPFGKMHGOVAAAAAElFTkSuQmCC
```

**Pull request merged**
